-- Adding users with roles --

INSERT INTO [User] VALUES ('admin', 'admin', 'Hedvig', 'Schmocker', 'administrator', 'hedvig@awa.se')
INSERT INTO [User] VALUES ('student', 'student', 'Petra', 'Mille', 'student', 'petra@awa.se')
INSERT INTO [User] VALUES ('teacher', 'teacher', 'Patrik', 'Jönsson', 'teacher', 'patrik@awa.se')

-- Adding quiz --

INSERT INTO Quiz VALUES ('2015-10-20', 'OOP Quiz', 'C#', 'En enkel objektorienterad quiz. Du har 20 min på dig att lösa den.')

-- Connecting quiz with teacher --

INSERT INTO UserQuiz VALUES ('3', '1')

-- Adding questions --

INSERT INTO Question VALUES ('2015-10-20', 'Vad är sant om följande kod?', 'class Student s1, s2; \n s1 = new Student(); \n s2 = new Student();', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vad är sant om följande kod?', 'class Sample\n{ private int i; public double j; private void DisplayData()\n{\nConsole.WriteLine(i + " " + j);\n}\npublic void ShowData()\n{\nConsole.WriteLine(i + " " + j);\n}\n}', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vilka av följande sätt är korrekt att skapa ett objekt av Sample()?', '1 Sample s = new Sample();\n2 Sample s;\n3 Sample s; s = new Sample();\n4 s = new Sample();\n', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vad blir utskriften av följande kod?', 'namespace ConsoleApplication\n{\nclass Sample\n{ int i; double j;\npublic void SetData(int i, double j)\n{ i = i; j = j;\n}\npublic void Display()\n{\nConsole.WriteLine(i + " " + j);\n}\n}\nclass MyProgram\n{\nstatic void Main(string[ ] args)\n{\nSample s1 = new Sample(); s1.SetData(10, 5.4);\ns1.Display();\n}\n}\n}\n', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vad är sant om följande kod?', 'Vad är sant om följande kod?\nnamespace ConsoleApplication\n{\nclass Sample\n{\npublic int index; public int[] arr = new int[10];\npublic void fun(int i, int val)\n{ arr[i] = val;\n}\n}\nclass MyProgram\n{\nstatic void Main(string[] args)\n{\nSample s = new Sample(); s.index = 20; Sample.fun(1, 5); s.fun(1, 5);\n}\n}\n}\n', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vad är sant om följande kod?', 'int i;\nint j = new int();\ni = 10;\nj = 20;\nString str;\nstr = i.ToString();\nstr = j.ToString(); ', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Vad är sant om följande kod?', 'namespace IndiabixConsoleApplication\n{\nclass Sample\n{ int i; double j;\npublic void SetData(int i, double j)\n{ this.i = i; this.j = j;\n}\npublic void Display()\n{\nConsole.WriteLine(i + " " + j);\n}\n}\nclass MyProgram\n{\nstatic void Main(string[ ] args)\n{\nSample s1 = new Sample(); s1.SetData(36, 5.4);\ns1.Display();\n}\n}\n}', '1')
INSERT INTO Question VALUES ('2015-10-20', 'Arv', 'Vilken klass ärver en Web Forms .aspx sida?', '1')
INSERT INTO Question VALUES ('2015-10-20', 'SQL', 'Vilken query lägger till en Contact som heter Kalle?', '1')

-- Connecting questions with quiz --

INSERT INTO QuizQuestion VALUES ('1', '1')
INSERT INTO QuizQuestion VALUES ('1', '2')
INSERT INTO QuizQuestion VALUES ('1', '3')
INSERT INTO QuizQuestion VALUES ('1', '4')
INSERT INTO QuizQuestion VALUES ('1', '5')
INSERT INTO QuizQuestion VALUES ('1', '6')
INSERT INTO QuizQuestion VALUES ('1', '7')
INSERT INTO QuizQuestion VALUES ('1', '8')
INSERT INTO QuizQuestion VALUES ('1', '9')

-- Addning answers --

INSERT INTO Answer VALUES ('s1 och s2 är exakt samma.', '0')
INSERT INTO Answer VALUES ('Innehållet i de två objekten är desamma.', '1')
INSERT INTO Answer VALUES ('s1 är en subklass till s2.', '0')
INSERT INTO Answer VALUES ('j kan inte vara public.', '0')
INSERT INTO Answer VALUES ('DisplayData() kan inte vara private.', '0')
INSERT INTO Answer VALUES ('DisplayData() kan inte nå j.', '0')
INSERT INTO Answer VALUES ('ShowData() kan inte nå i.', '0')
INSERT INTO Answer VALUES ('Det är inget fel på koden.', '1')
INSERT INTO Answer VALUES ('1 och 3.', '1')
INSERT INTO Answer VALUES ('2 och 4.', '0')
INSERT INTO Answer VALUES ('1, 2, 3.', '0')
INSERT INTO Answer VALUES ('1 och 4.', '0')
INSERT INTO Answer VALUES ('Inget av alternativen.', '0')
INSERT INTO Answer VALUES ('0 0', '1')
INSERT INTO Answer VALUES ('10 5.4', '0')
INSERT INTO Answer VALUES ('10 5.400000', '0')
INSERT INTO Answer VALUES ('10 5', '0')
INSERT INTO Answer VALUES ('Inget av alternativen.', '0')
INSERT INTO Answer VALUES ('s.index kommer gå fel eftersom index är public.', '0')
INSERT INTO Answer VALUES ('s.fun(1,5) kommer fungera korrekt.', '1')
INSERT INTO Answer VALUES ('Sample.fun(1, 5) kommer sätte värdet 5 i arr[1].', '0')
INSERT INTO Answer VALUES ('Efter som arr är en array kan den inte vara public.', '0')
INSERT INTO Answer VALUES ('Inget fel alls.', '1')
INSERT INTO Answer VALUES ('int j = new int(); kommer inte fungera.', '0')
INSERT INTO Answer VALUES ('Eftersom i och j är datatyper kan vi inte använda ToString().', '0')
INSERT INTO Answer VALUES ('0 0.0', '0')
INSERT INTO Answer VALUES ('36 5.4', '0')
INSERT INTO Answer VALUES ('36 5.400000...', '1')
INSERT INTO Answer VALUES ('36 5', '0')
INSERT INTO Answer VALUES ('Inget av ovanstående.', '0')
INSERT INTO Answer VALUES ('System.Web.UI.Forms', '0')
INSERT INTO Answer VALUES ('System.Web.UI.WebForm', '0')
INSERT INTO Answer VALUES ('System.Web.UI.Page', '1')
INSERT INTO Answer VALUES ('System.Web.UI.WebPage', '0')
INSERT INTO Answer VALUES ('update contact set Firstname=’Kalle’', '0')
INSERT INTO Answer VALUES ('select * from Contact where Firstname=’Kalle’', '0')
INSERT INTO Answer VALUES ('insert into Contact (Firstname) values (‘Kalle’)', '1')
INSERT INTO Answer VALUES ('execute sp_DeleteKalleFromContatcs ‘Kalle’', '0')

-- Connection answers with questions --

INSERT INTO QuestionAnswer VALUES ('1', '1')
INSERT INTO QuestionAnswer VALUES ('1', '2')
INSERT INTO QuestionAnswer VALUES ('1', '3')
INSERT INTO QuestionAnswer VALUES ('2', '4')
INSERT INTO QuestionAnswer VALUES ('2', '5')
INSERT INTO QuestionAnswer VALUES ('2', '6')
INSERT INTO QuestionAnswer VALUES ('2', '7')
INSERT INTO QuestionAnswer VALUES ('2', '8')
INSERT INTO QuestionAnswer VALUES ('3', '9')
INSERT INTO QuestionAnswer VALUES ('3', '10')
INSERT INTO QuestionAnswer VALUES ('3', '11')
INSERT INTO QuestionAnswer VALUES ('3', '12')
INSERT INTO QuestionAnswer VALUES ('3', '13')
INSERT INTO QuestionAnswer VALUES ('4', '14')
INSERT INTO QuestionAnswer VALUES ('4', '15')
INSERT INTO QuestionAnswer VALUES ('4', '16')
INSERT INTO QuestionAnswer VALUES ('4', '17')
INSERT INTO QuestionAnswer VALUES ('4', '18')
INSERT INTO QuestionAnswer VALUES ('5', '19')
INSERT INTO QuestionAnswer VALUES ('5', '20')
INSERT INTO QuestionAnswer VALUES ('5', '21')
INSERT INTO QuestionAnswer VALUES ('5', '22')
INSERT INTO QuestionAnswer VALUES ('6', '23')
INSERT INTO QuestionAnswer VALUES ('6', '24')
INSERT INTO QuestionAnswer VALUES ('6', '25')
INSERT INTO QuestionAnswer VALUES ('7', '26')
INSERT INTO QuestionAnswer VALUES ('7', '27')
INSERT INTO QuestionAnswer VALUES ('7', '28')
INSERT INTO QuestionAnswer VALUES ('7', '29')
INSERT INTO QuestionAnswer VALUES ('7', '30')
INSERT INTO QuestionAnswer VALUES ('8', '31')
INSERT INTO QuestionAnswer VALUES ('8', '32')
INSERT INTO QuestionAnswer VALUES ('8', '33')
INSERT INTO QuestionAnswer VALUES ('8', '34')
INSERT INTO QuestionAnswer VALUES ('9', '35')
INSERT INTO QuestionAnswer VALUES ('9', '36')
INSERT INTO QuestionAnswer VALUES ('9', '37')
INSERT INTO QuestionAnswer VALUES ('9', '38')